#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/Documents/techyon -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
  if [[ "$selected_name" == *techyon-ui ]]; then
    tmux new-session -ds $selected_name -c $selected -n lvim "lvim $(find $selected/services -mindepth 1 -maxdepth 1 -type d | fzf)/."
    tmux new-window -dt $selected_name -c $selected -n node mprocs
    tmux new-window -dt $selected_name -c $selected -n shell
  else
    tmux new-session -ds $selected_name -c $selected -n lvim "lvim ."
    tmux new-window -dt $selected_name -c $selected -n shell
  fi
fi

tmux switch-client -t $selected_name
