#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/Documents/techyon -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
  if [[ "$selected_name" == *techyon-ui ]]; then
    selected_service=$(find $selected/services -mindepth 1 -maxdepth 1 -type d | fzf)
    tmux new-session -ds $selected_name -c $selected -n vim
    tmux send-keys -t $selected_name':vim' "vim $selected_service/." Enter
    tmux new-window -dt $selected_name -c $selected_service -n mprocs 
    tmux send-keys -t $selected_name':mprocs' "mprocs --npm" Enter
    tmux new-window -dt $selected_name -c $selected_service -n shell
  else
    tmux new-session -ds $selected_name -c $selected -n vim
    tmux send-keys -t $selected_name':vim' "vim ." Enter
    tmux new-window -dt $selected_name -c $selected -n shell
  fi
fi

tmux switch-client -t $selected_name
